 github: [metadata]
 title: butt first coffee
 encoding: UTF-8
 description: Hi, my name's Katherine. I'm a software developer.
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 #theme: jekyll-theme-tactile
 gfm_quirks: paragraph_end
