 github: [metadata]
 title: butt first coffee
 encoding: UTF-8
 description: Welcome to Katherine Maack's personal site
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-tactile
 gfm_quirks: paragraph_end
